version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://db:5432/trail_db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trail_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
