CREATE SEQUENCE seq_class_id;
CREATE TABLE trail_class
(
    class_id INTEGER NOT NULL DEFAULT nextval('seq_class_id'),
    class_code VARCHAR(255),
    description VARCHAR(255),
    class_name VARCHAR(255),
    CONSTRAINT pk_trail_class PRIMARY KEY (class_id)
);

CREATE SEQUENCE seq_trail_difficulty;
CREATE TABLE trail_difficulty(
	difficulty_id INTEGER NOT NULL DEFAULT nextval('seq_trail_difficulty'),
	difficulty VARCHAR(255),
	description VARCHAR(255),
	CONSTRAINT pk_trail_difficulty PRIMARY KEY (difficulty_id)
);

CREATE SEQUENCE seq_trail_id;
CREATE TABLE trail(
	trail_id INTEGER NOT NULL DEFAULT nextval('seq_trail_id'),
	access_name VARCHAR(255),
	access_id VARCHAR(50),
	access_type VARCHAR(50),
	address VARCHAR(255),
	aka VARCHAR(255),
	date_from DATE,
	date_to DATE,
	restroom BOOLEAN,
	picnic BOOLEAN,
	fishing BOOLEAN,
	fee BOOLEAN,
	bike_rack BOOLEAN,
	bike_trail BOOLEAN,
	grills BOOLEAN,
	horse_trail VARCHAR(255),
	recycle_bin BOOLEAN,
	dog_compost BOOLEAN,
	th_leash BOOLEAN,
	dog_tube INTEGER,
	trash_cans INTEGER,
	parking_space INTEGER,
	ada_surface VARCHAR(255),
	ada_facility BOOLEAN,
	ada_facility_name VARCHAR(255),
	ada_parking BOOLEAN,
	ada_parking_no INTEGER,
	ada_toilet BOOLEAN,
	ada_fishing BOOLEAN,
	ada_camping BOOLEAN,
	ada_picnic BOOLEAN,
	trail_class_id INTEGER,
	ada_trail_difficulty_id INTEGER,

	CONSTRAINT pk_trail PRIMARY KEY (trail_id),
	CONSTRAINT fk_trail_trail_class FOREIGN KEY (trail_class_id) REFERENCES trail_class (class_id),
	CONSTRAINT fk_trail_trail_difficulty FOREIGN KEY (ada_trail_difficulty_id) REFERENCES trail_difficulty (difficulty_id)
);

CREATE SEQUENCE seq_database_version_history_id;
CREATE TABLE database_version_history (
    database_version_history_id INT NOT NULL DEFAULT nextval('seq_database_version_history_id'),
    version text NOT NULL,
    applied_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT pk_database_version_history PRIMARY KEY (database_version_history_id),
    CONSTRAINT uq_database_version_history_version UNIQUE (version),
    CONSTRAINT ck_database_version_history_version CHECK (version <> '' AND version NOT LIKE ' %' AND version NOT LIKE '% ')
);

INSERT INTO trail_class (class_code, description, class_name) VALUES
	('T1', 'T1 name', 'T1 description'),
	('T2', 'T2 name', 'T2 description'),
	('T3', 'T3 name', 'T3 description');
	
INSERT INTO trail_difficulty (difficulty, description) VALUES
	('Easy', 'desc1'),
	('Easy/Moderate', 'desc2'),
	('Moderate', 'desc3'),
	('Moderate/Difficult', 'desc4'),
	('Moderate/Most Difficult', 'desc5'),
	('Difficult', 'desc6'),
	('Most Difficult', 'desc7'),
	('Not Available', 'desc8');

INSERT INTO trail(
	access_name, 
	access_id, 
	access_type, 
	address, 
	aka, 
	date_from, 
	date_to, 
	restroom, 
	picnic, 
	fishing, 
	fee, 
	bike_rack, 
	bike_trail, 
	grills, 
	horse_trail, 
	recycle_bin, 
	dog_compost, 
	th_leash, 
	dog_tube, 
	trash_cans, 
	parking_space, 
	ada_surface, 
	ada_facility, 
	ada_facility_name, 
	ada_parking, 
	ada_parking_no, 
	ada_toilet, 
	ada_fishing, 
	ada_camping, 
	ada_picnic, 
	trail_class_id, 
	ada_trail_difficulty_id)
VALUES (
	'Flagstaff Summit West',
	'279',
	'TH',
	'621 Flagstaff Summit Rd',
	null,
	'2005-12-31',
	'2099-12-31',
	true,
	true,
	false,
	true,
	false,
	false,
	true,
	'Not Recommended',
	true,
	false,
	true,
	1,
	4,
	12,
	'Asphalt',
	true,
	'Wood Shelter',
	true,
	null,
	true,
	false,
	false,
	true,
	3,
	3
),
	('Flagstaff Summit East',
	'277',
	'TH',
	'790 Flagstaff Summit Rd',
	null,
	'2005-12-31',
	'2099-12-31',
	true,
	true,
	false,
	true,
	true,
	false,
	true,
	'Not Recommended',
	true,
	false,
	true,
	1,
	6,
	56,
	'Asphalt',
	true,
	'Nature Center',
	true,
	null,
	true,
	false,
	false,
	true,
	3,
	6
),
	('East Boulder Trail at White Rocks',
	'502a',
	'TH',
	'4705 95th St',
	null,
	'2005-12-31',
	'2099-12-31',
	false,
	false,
	false,
	false,
	true,
	true,
	false,
	'Not Recommended',
	false,
	false,
	true,
	0,
	1,
	6,
	'no',
	false,
	null,
	false,
	null,
	false,
	false,
	false,
	false,
	1,
	8
),
	('Buckingham Park',
	'417',
	'TH',
	'2500 Left-hand Canyon Dr',
	null,
	'2005-12-31',
	'2099-12-31',
	true,
	true,
	true,
	false,
	true,
	false,
	true,
	'Possible',
	true,
	false,
	true,
	1,
	2,
	35,
	'Crusher Fines',
	false,
	null,
	true,
	null,
	true,
	false,
	false,
	true,
	3,
	6
),
	('Settlers Park',
	'286',
	'TH',
	'101 Pearl St',
	null,
	'2005-12-31',
	'2099-12-31',
	false,
	true,
	true,
	false,
	true,
	false,
	false,
	'Not Recommended',
	true,
	false,
	true,
	1,
	2,
	27,
	'Cement/Crusher',
	false,
	null,
	true,
	null,
	false,
	false,
	false,
	true,
	2,
	1
);